backend:
  name: git-gateway
  branch: main

site_url: https://bizerra.shop

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "tutorial"
    label: "Guia de Uso do Painel"
    description: "Um guia completo para o ajudar a gerir o seu site."
    files:
      - name: "guia"
        label: "Tutorial"
        file: "admin/tutorial.md"
        fields:
          - { name: body, widget: markdown, readonly: true }

  - name: "config_gerais"
    label: "Configurações Gerais"
    description: "Edite aqui as informações gerais do site, como título, links e cores."
    files:
      - name: "settings"
        label: "Configurações do Site"
        file: "_data/settings.json"
        fields:
          - { label: "Título Principal do Site", name: "title", widget: "string" }
          - { label: "Slogan abaixo do Título", name: "tagline", widget: "string" }
          - label: "Cores do Tema"
            name: "theme_colors"
            widget: "object"
            fields:
              - { label: "Cor Principal (Destaques, botões, links)", name: "primary", widget: "color" }
              - { label: "Cor de Fundo (Cor escura do site)", name: "background", widget: "color" }
              - { label: "Cor do Texto (Cor clara do site)", name: "text", widget: "color" }
          - label: "Links de Suporte"
            name: "links"
            widget: "object"
            fields:
              - { label: "Link do Grupo WhatsApp", name: "group_whatsapp", widget: "string" }
              - { label: "Link do Suporte Telegram", name: "support_telegram", widget: "string" }
              - { label: "Link do Grupo Telegram", name: "group_telegram", widget: "string" }
              - { label: "Número do Suporte WhatsApp (com +55)", name: "support_whatsapp_number", widget: "string" }
          - label: "Cupom de Desconto"
            name: "coupon"
            widget: "object"
            fields:
              - { label: "Código do Cupom (ex: BZR10)", name: "code", widget: "string" }
              - { label: "Percentagem de Desconto (ex: 0.1 para 10%)", name: "percentage", widget: "number" }

  - name: "produtos"
    label: "Produtos e Assinaturas"
    description: "Adicione, edite ou remova produtos e os seus planos."
    files:
      - name: "lista_produtos"
        label: "Lista de Produtos"
        file: "_data/products.json"
        fields:
          - name: "items"
            label: "Produtos"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "ID (número único, não repita)", name: "id", widget: "number" }
              - { label: "Nome do Produto", name: "name", widget: "string" }
              - { label: "Ícone (ex: fas fa-tv)", name: "icon", widget: "string" }
              - { label: "Categoria", name: "category", widget: "string" }
              - { label: "Descrição Curta", name: "description", widget: "string" }
              - label: "Variações do Produto (planos)"
                name: "variations"
                widget: "list"
                summary: "{{fields.name}} - R$ {{fields.price}}"
                fields:
                  - { label: "Nome da Variação", name: "name", widget: "string" }
                  - { label: "Preço (use ponto para centavos, ex: 19.90)", name: "price", widget: "number", value_type: "float", step: 0.01, min: 0 }
                  - { label: "Detalhes", name: "details", widget: "text" }
                  - { label: "Nota Importante", name: "important", widget: "text" }
  
  - name: "monetizacao"
    label: "Monetização (Google AdSense)"
    description: "Cole aqui os códigos de anúncio do Google AdSense."
    files:
      - name: "adsense"
        label: "Códigos de Anúncio"
        file: "_data/settings.json"
        fields:
          - { label: "Script do Cabeçalho (da tag <head>)", name: "adsense.head_script", widget: "text", required: false }
          - { label: "Código do Bloco de Anúncios 1 (ex: Banner no topo)", name: "adsense.ad_unit_1", widget: "text", required: false }
          - { label: "Código do Bloco de Anúncios 2 (ex: Banner no rodapé)", name: "adsense.ad_unit_2", widget: "text", required: false }